#For shared directories on windows the path should be like
# path: "\\\\1.2.3.4\\abc\\def\\ProductI

# Make sure the metric prefix ends with a |

#Use this metric prefix when SIM is enabled.
metricPrefix: "Custom Metrics|Metric Loader|"

# To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/LATEST/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: "Server|Component:<Component_ID OR Component_Name>|Custom Metrics|File Watcher|"

pathsToProcess:
# Matching all files and directories within TestFiles, recursively
- displayName: "TestPath"
  path: "./test.csv"



numberOfThreads: 20 #One thread per base directory + 1

# Generate a custom dashboard based on the provided template
customDashboard:
  enabled: false
  dashboardName: "Metric Loader Dashboard"
  #  sslCertCheckEnabled: true
  # Update the path to the dashboard file.
  pathToSIMDashboard: "monitors/MetricLoader/SIMDashboard.json"
  pathToNormalDashboard:
  periodicDashboardCheckInSeconds: 60

# If any of the following fields are not set, the values of the specific fields are set from the system properties of the corresponding fields as specified in the comments.
# If the system properties are not set for the field, then the data is retrieved from machine agent configFile. Please refer to ControllerInfoFactory for more details.
controllerInfo:
  controllerHost: "test"
  controllerPort: 8080
  account: "customer1"
  username: "user1"
  password: "welcome"
  encryptedPassword: ""
  encryptionKey: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: "test"
  machinePath: ""
  simEnabled: true
  applicationName: "test"
  tierName: "test"
  nodeName: "test"